// stubs/react/resources/js/components/linked-account.tsx
import type { SocialAccount, SocialiteUi } from '@/types/socialite-ui';
import { SocialiteProviderIcon } from '@/components/socialite-provider-icon';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogTitle,
    DialogTrigger
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import InputError from '@/components/input-error';
import { FormEventHandler, useRef } from 'react';
import { useForm } from '@inertiajs/react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { UserInfo } from '@/components/user-info';

interface LinkedAccountProps {
    socialAccount: SocialAccount;
    socialiteUi: SocialiteUi;
}

export default function LinkedAccount({ socialAccount, socialiteUi }: LinkedAccountProps) {
    const passwordInput = useRef<HTMLInputElement>(null);

    const { patch, processing: updatingAvatar } = useForm({
        avatar: socialAccount.avatar,
    });

    const updateAvatar: FormEventHandler = (e) => {
        e.preventDefault();

        patch(route('profile.avatar.update'), {
            preserveScroll: true,
        });
    };


    const { data, setData, delete: destroy, processing, reset, errors, clearErrors } = useForm({
        password: '',
    });

    const unlinkAccount: FormEventHandler = (e) => {
        e.preventDefault();

        destroy(route('linked-accounts.destroy', { account: socialAccount.id }), {
            preserveScroll: true,
            onSuccess: () => closeModal(),
            onError: () => passwordInput.current?.focus(),
            onFinish: () => reset(),
        });
    };

    const closeModal = () => {
        clearErrors();
        reset();
    };

    return (
      <div className="flex px-6 py-4 gap-4 border rounded-xl">
          <div className="grid w-full md:grid-cols-2 items-center gap-6">
              <div className="flex flex-row-reverse md:flex-row justify-between md:justify-start md:items-center gap-3">
                  <SocialiteProviderIcon provider={socialAccount.provider.id} className="h-6 w-6 md:h-8 md:w-8"/>

                  <div className="flex items-center justify-center gap-2">
                      <UserInfo user={socialAccount} showEmail={true} />
                  </div>
              </div>

              <div className="flex flex-col md:flex-row items-center justify-between md:justify-end gap-3 md:gap-2">
                  <form onSubmit={updateAvatar} className="flex w-full md:w-auto">
                      <Button variant="link" type="submit" disabled={updatingAvatar} className="w-full">
                          Use Avatar
                      </Button>
                  </form>

                  {!socialiteUi.hasPassword && (
                    <Tooltip delayDuration={0}>
                        <TooltipTrigger className="flex w-full md:w-auto">
                            <Button variant="destructive" disabled={!socialiteUi.hasPassword} className="w-full">
                                Unlink
                            </Button>
                        </TooltipTrigger>
                        <TooltipContent>
                            <p>Set a password to unlink this account</p>
                        </TooltipContent>
                    </Tooltip>
                  )}

                  {socialAccount && socialiteUi.hasPassword && (
                    <Dialog>
                        <DialogTrigger asChild>
                            <Button variant="destructive" disabled={!socialiteUi.hasPassword} className="w-full md:w-auto">
                                Unlink
                            </Button>
                        </DialogTrigger>
                        <DialogContent>
                            <DialogTitle>Are you sure you want to unlink this account?</DialogTitle>
                            <DialogDescription>Once unlinked, you will no longer be able to sign in with this account.</DialogDescription>
                            <form className="space-y-6" onSubmit={unlinkAccount}>
                                <div className="grid gap-2">
                                    <Label htmlFor="password" className="sr-only">
                                        Password
                                    </Label>

                                    <Input
                                      id="password"
                                      type="password"
                                      name="password"
                                      ref={passwordInput}
                                      value={data.password}
                                      onChange={(e) => setData('password', e.target.value)}
                                      placeholder="Password"
                                      autoComplete="current-password"
                                    />

                                    <InputError message={errors.password} />
                                </div>

                                <DialogFooter className="gap-2">
                                    <DialogClose asChild>
                                        <Button variant="secondary" onClick={closeModal}>
                                            Cancel
                                        </Button>
                                    </DialogClose>

                                    <Button variant="destructive" disabled={processing} asChild>
                                        <button type="submit">Delete account</button>
                                    </Button>
                                </DialogFooter>
                            </form>
                        </DialogContent>
                    </Dialog>
                  )}
              </div>
          </div>
      </div>
    );
}

// stubs/vue/resources/js/components/LinkedAccount.vue
<script setup lang="ts">
import type { SocialiteUi, SocialAccount } from '@/types/socialite-ui';
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import SocialiteProviderIcon from '@/components/SocialiteProviderIcon.vue';
import UserInfo from '@/components/UserInfo.vue';
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import {
   Dialog, DialogClose,
   DialogContent,
   DialogDescription,
   DialogFooter,
   DialogTitle,
   DialogTrigger
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import InputError from '@/components/InputError.vue';

interface Props {
   socialAccount: SocialAccount;
   socialiteUi: SocialiteUi;
}

const { socialAccount, socialiteUi } = defineProps<Props>();

const passwordInput = ref<HTMLInputElement | null>(null);

const updateAvatarForm = useForm({
   avatar: socialAccount.avatar,
});

const updateAvatar = () => {
   updateAvatarForm.patch(route('profile.avatar.update'), {
      onFinish: () => {
         updateAvatarForm.reset();
      },
   });
};

const unlinkAccountForm = useForm({
   password: '',
});

const unlinkAccount = (e: Event) => {
   e.preventDefault();

   unlinkAccountForm.delete(route('linked-accounts.destroy', { account: socialAccount.id }), {
      preserveScroll: true,
      onSuccess: () => closeModal(),
      onError: () => passwordInput.value?.focus(),
      onFinish: () => unlinkAccountForm.reset(),
   });
};

const closeModal = () => {
   unlinkAccountForm.clearErrors();
   unlinkAccountForm.reset();
};
</script>

<template>
   <div class="flex px-6 py-4 gap-4 border rounded-xl">
      <div class="grid w-full md:grid-cols-2 items-center gap-4">
         <div class="flex flex-row-reverse md:flex-row justify-between md:justify-start items-center gap-3">
            <SocialiteProviderIcon :provider="socialAccount.provider.id" class="h-8 w-8"/>

            <div class="flex items-center justify-center gap-2">
               <UserInfo :user="socialAccount" :showEmail="true" />
            </div>
         </div>

         <div class="flex flex-col md:flex-row items-center justify-between md:justify-end gap-3 md:gap-2">
            <form @submit.prevent="updateAvatar" class="flex w-full md:w-auto">
               <Button variant="link" :disabled="updateAvatarForm.processing" class="flex w-full">
                  Use Avatar
               </Button>
            </form>

            <TooltipProvider v-if="!socialiteUi.hasPassword">
               <Tooltip :delay-duration="0">
                  <TooltipTrigger class="w-full md:w-auto">
                     <Button variant="destructive" :disabled="!socialiteUi.hasPassword">
                        Unlink
                     </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                     <p>Set a password to unlink this account</p>
                  </TooltipContent>
               </Tooltip>
            </TooltipProvider>

            <template v-if="socialAccount && socialiteUi.hasPassword">
               <Dialog>
                  <DialogTrigger asChild>
                     <Button variant="destructive" :disabled="! socialiteUi.hasPassword" class="w-full md:w-auto">
                        Unlink
                     </Button>
                  </DialogTrigger>
                  <DialogContent>
                     <DialogTitle>Are you sure you want to unlink this account?</DialogTitle>
                     <DialogDescription>Once unlinked, you will no longer be able to sign in with this socialAccount.</DialogDescription>

                     <form @submit.prevent="unlinkAccount">
                        <div class="space-y-6">
                           <div class="grid gap-2">
                              <Label htmlFor="password">Password</Label>
                              <Input
                                 id="password"
                                 type="password"
                                 class="mt-1 block w-full"
                                 v-model="unlinkAccountForm.password"
                                 required
                                 autocomplete="current-password"
                                 autofocus
                              />

                              <InputError :message="unlinkAccountForm.errors.password" />
                           </div>

                           <DialogFooter>
                              <DialogClose>
                                 <Button variant="link" :onclick="closeModal">
                                    Cancel
                                 </Button>
                              </DialogClose>

                              <Button variant="destructive" :disabled="unlinkAccountForm.processing" as-child>
                                 <button type="submit">Unlink Account</button>
                              </Button>
                           </DialogFooter>
                        </div>
                     </form>
                  </DialogContent>
               </Dialog>
            </template>
         </div>
      </div>
   </div>
</template>
